// Copyright (c) Krosmoz 2025.
// Krosmoz licenses this file to you under the MIT license.
// See the license here https://github.com/AerafalGit/Krosmoz/blob/main/LICENSE.

namespace Krosmoz.Protocol.Enums;

public enum ProtocolConstants
{
	MapCellCount = 560,
	MaxLevel = 200,
	MaxGuildLevel = 200,
	MaxMountLevel = 100,
	MaxChatLen = 512,
	UserMaxChatLen = 256,
	MinLoginLen = 3,
	MaxLoginLen = 50,
	MinPlayerNameLen = 2,
	MaxPlayerNameLen = 20,
	MinNickLen = 2,
	MaxNickLen = 30,
	MinGuildnameLen = 3,
	MaxGuildnameLen = 30,
	MinAlliancenameLen = 3,
	MaxAlliancenameLen = 30,
	MinAlliancetagLen = 3,
	MaxAlliancetagLen = 5,
	MaxPlayerColor = 5,
	MaxEntityColor = 8,
	MaxPlayersPerTeam = 8,
	MaxMembersPerParty = 8,
	MaxGuestsPerParty = 7,
	MaxMembersPerArenaParty = 5,
	MaxMonstersInGroupOnMap = 16,
	MaxChatObjectRef = 16,
	NotEquiped = 63,
	MaxEquiped = 255,
	MaxJobsPerCharacter = 6,
	MaxCraftSlot = 9,
	MaxJobLevel = 100,
	MaxHonor = 20000,
	MaxShortcut = 99,
	MaxArenaRank = 2300,
	CharMinLevelArena = 50,
	CharMinLevelRide = 60,
	MaxDungeonRegister = 10,
	MinRideNameLen = 0,
	MaxRideNameLen = 16,
	MaxEffectsCount = 100,
	MaxLockableCodeLen = 8,
	MaxPresetItemCount = 24,
	MinObjCountByXfert = 1,
	MaxObjCountByXfert = 1000,
	MaxObjectEffectStringLen = 30,
	MaxPlayerOrAccountNameLen = 31
}
