// Copyright (c) Krosmoz 2025.
// Krosmoz licenses this file to you under the MIT license.
// See the license here https://github.com/AerafalGit/Krosmoz/blob/main/LICENSE.

namespace Krosmoz.Protocol.Enums.Custom;

public enum AreaIds
{
	Amakna = 0,
	LileDesWabbits = 1,
	LileDeMoon = 2,
	Prison = 3,
	Tainela = 4,
	Sufokia = 5,
	ForetDesAbraknydes = 6,
	Bonta = 7,
	PlaineDeCania = 8,
	Brakmar = 11,
	LandesDeSidimote = 12,
	TerritoireDesDopeuls = 13,
	VillageDesBrigandins = 14,
	FoireDuTrool = 15,
	Astrub = 18,
	PandalaNeutre = 19,
	PandalaEau = 20,
	PandalaTerre = 21,
	PandalaFeu = 22,
	PandalaAir = 23,
	PandalaDonjon = 24,
	LeLabyrintheDuDragonCochon = 26,
	DonjonAbraknyde = 27,
	MontagneDesKoalaks = 28,
	DonjonDesTofus = 29,
	LileDuMinotoror = 30,
	CentreDuLabyrintheDuMinotoror = 31,
	LaBibliothequeDuMaitreCorbac = 32,
	DonjonDesCanides = 33,
	CaverneDuKoulosse = 34,
	SanctuaireDesFamiliers = 36,
	DonjonDesCraqueleurs = 37,
	DonjonDesBworks = 39,
	DonjonDesScarafeuilles = 40,
	DonjonDesChamps = 41,
	IleDeNowel = 42,
	DonjonDuDragonCochon = 43,
	DonjonDesDragoeufs = 44,
	Incarnam = 45,
	IleDOtomai = 46,
	VillageDesZoths = 47,
	IleDeFrigost = 48,
	IleDeSakai = 49,
	ArchipelDeVulkania = 50,
}
