// Copyright (c) Krosmoz 2025.
// Krosmoz licenses this file to you under the MIT license.
// See the license here https://github.com/AerafalGit/Krosmoz/blob/main/LICENSE.

namespace Krosmoz.Protocol.Enums.Custom;

public enum DungeonIds
{
	DonjonDesBouftous = 1,
	BibliothequeDuMaitreCorbac = 3,
	CentreDuLabyrintheDuMinotoror = 4,
	AntreDuDragonCochon = 6,
	DonjonDesDragoeufs = 7,
	DonjonDesChamps = 8,
	DonjonDesAbraknydes = 9,
	DonjonDuCheneMou = 10,
	DonjonDesBlops = 11,
	CaverneDesBulbes = 12,
	DonjonDesBworks = 13,
	DonjonDuBworker = 14,
	DonjonDesCanides = 15,
	TerrierDuWaWabbit = 17,
	DonjonDesCraqueleurs = 18,
	DonjonEnsable = 19,
	DonjonDesFirefoux = 20,
	DonjonDesForgerons = 21,
	DonjonFungus = 22,
	GelaxiemeDimension = 24,
	GrotteHesque = 25,
	DonjonDIncarnam = 26,
	DonjonKanniboul = 27,
	CanopeeDuKimbo = 28,
	DonjonDesKitsounes = 29,
	CaverneDuKoulosse = 30,
	AntreDuKralamoureGeant = 31,
	NidDuKwakwa = 32,
	DonjonDesLarves = 33,
	MaisonFantome = 34,
	LaboratoireDeBrumenTinctorias = 35,
	DonjonDeNowel = 36,
	CaverneDeNowel = 37,
	MaisonDuPapaNowel = 38,
	CaleDeLArcheDOtomai = 39,
	RepaireDesPandikazes = 40,
	GouletDuRasboul = 41,
	DonjonDesRatsDeBonta = 42,
	DonjonDesRatsDeBrakmar = 43,
	DonjonDesRatsDuChateauDAmakna = 44,
	DonjonDesScarafeuilles = 45,
	RepaireDeSkeunk = 46,
	DonjonDesSquelettes = 47,
	DonjonDesTofus = 48,
	AntreDuBlopMulticoloreRoyal = 49,
	TofulaillerRoyal = 50,
	LaboratoireDuTynril = 51,
	ChateauDuWaWabbit = 52,
	SalleDuMinotot = 53,
	SerreDuRoyalmouth = 54,
	ExcavationDuMansotRoyal = 55,
	EpaveDuGrolandaisViolent = 56,
	HypogeeDeLObsidiantre = 57,
	TaniereGivrefoux = 58,
	AntreDuKorriandre = 59,
	CavernesDuKolosso = 60,
	AntichambreDesGloursons = 61,
	DonjonDeLaMineDeSakai = 62,
	DonjonDesTofusEtDuTofuRoyal = 63,
	RepaireDeDaigoro = 64,
	SanctuaireDesFamiliers = 65,
	PotagerDHalouine = 66,
	TransporteurDeSylargh = 67,
	SalonsPrivesDeKlime = 68,
	ForgefroideDeMissizFrizz = 69,
	LaboratoireDeNileza = 70,
	DonjonDuComteHarebourg = 71,
}
