// Copyright (c) Krosmoz 2025.
// Krosmoz licenses this file to you under the MIT license.
// See the license here https://github.com/AerafalGit/Krosmoz/blob/main/LICENSE.

namespace Krosmoz.Protocol.Enums.Custom;

public enum EmoticonIds
{
	Sasseoir = 1,
	Sallonger = 19,
	CroiserLesBras = 14,
	MainsSurLesHanches = 34,
	Sagenouiller = 58,
	SeProsterner = 66,
	MontrerDuDoigt = 15,
	Saluer = 9,
	FaireUnSigneDeLaMain = 2,
	FaireUnBisou = 10,
	Coucou = 49,
	AttirerLattention = 73,
	SalutVulkain = 65,
	GonflerSesMuscles = 68,
	EtendardDeGuilde = 97,
	EtendardDAlliance = 98,
	BrandirSonBouclier = 96,
	BrandirSonArme = 6,
	DefouraillerSonArme = 93,
	SeMettreEnColere = 4,
	PoingLeve = 71,
	MontrerSaPeur = 5,
	Facepaume = 76,
	Applaudir = 3,
	Encourager = 88,
	Rire = 24,
	Pleurer = 26,
	Refuser = 25,
	Halouine = 90,
	Fleurs = 35,
	Manolias = 38,
	OffrirUnCadeau = 56,
	JouerAuxCartes = 50,
	LeverLePouce = 43,
	BaisserLePouce = 44,
	PiedDeNez = 72,
	SuperHeros = 51,
	Piou = 48,
	DevorerUneCawotte = 101,
	Bailler = 41,
	SeFrotterLesMains = 75,
	EtreFrigorifie = 36,
	Eternuer = 37,
	AvoirFroid = 39,
	AvoirChaud = 67,
	Motus = 74,
	LacherLesGaz = 8,
	Trace = 33,
	JouerDeLaFlute = 7,
	Ecrire = 92,
	LireUnLivre = 30,
	LireUneCarte = 69,
	LongueVue = 84,
	Clepsydre = 99,
	Champion = 21,
	AttitudeTemeraire = 57,
	AuraDePuissance = 22,
	AuraVampyrique = 23,
	AuraBleuteeDeLornithorynqueAncestral = 40,
	AuraDeNelween = 55,
	BoireUnePotion = 61,
	BoireUneBiere = 18,
	Manger = 17,
	FioleDeChichala = 91,
	EauDeLaFontaineDeNoffoub = 100,
	Ogrine = 70,
	Pierre = 11,
	Feuille = 12,
	Ciseaux = 13,
	Lezard = 63,
	Stok = 64,
}
