// Copyright (c) Krosmoz 2025.
// Krosmoz licenses this file to you under the MIT license.
// See the license here https://github.com/AerafalGit/Krosmoz/blob/main/LICENSE.

namespace Krosmoz.Protocol.Enums.Custom;

public enum MountIds
{
	DragodindeAmandeSauvage = 1,
	DragodindeEbene = 3,
	DragodindeRousseSauvage = 6,
	DragodindeEbeneEtIvoire = 9,
	DragodindeRousse = 10,
	DragodindeIvoireEtRousse = 11,
	DragodindeEbeneEtRousse = 12,
	DragodindeTurquoise = 15,
	DragodindeIvoire = 16,
	DragodindeIndigo = 17,
	DragodindeDoree = 18,
	DragodindePourpre = 19,
	DragodindeAmande = 20,
	DragodindeEmeraude = 21,
	DragodindeOrchidee = 22,
	DragodindePrune = 23,
	DragodindeAmandeEtDoree = 33,
	DragodindeAmandeEtEbene = 34,
	DragodindeAmandeEtEmeraude = 35,
	DragodindeAmandeEtIndigo = 36,
	DragodindeAmandeEtIvoire = 37,
	DragodindeAmandeEtRousse = 38,
	DragodindeAmandeEtTurquoise = 39,
	DragodindeAmandeEtOrchidee = 40,
	DragodindeAmandeEtPourpre = 41,
	DragodindeDoreeEtEbene = 42,
	DragodindeDoreeEtEmeraude = 43,
	DragodindeDoreeEtIndigo = 44,
	DragodindeDoreeEtIvoire = 45,
	DragodindeDoreeEtRousse = 46,
	DragodindeDoreeEtTurquoise = 47,
	DragodindeDoreeEtOrchidee = 48,
	DragodindeDoreeEtPourpre = 49,
	DragodindeEbeneEtEmeraude = 50,
	DragodindeEbeneEtIndigo = 51,
	DragodindeEbeneEtTurquoise = 52,
	DragodindeEbeneEtOrchidee = 53,
	DragodindeEbeneEtPourpre = 54,
	DragodindeEmeraudeEtIndigo = 55,
	DragodindeEmeraudeEtIvoire = 56,
	DragodindeEmeraudeEtRousse = 57,
	DragodindeEmeraudeEtTurquoise = 58,
	DragodindeEmeraudeEtOrchidee = 59,
	DragodindeEmeraudeEtPourpre = 60,
	DragodindeIndigoEtIvoire = 61,
	DragodindeIndigoEtRousse = 62,
	DragodindeIndigoEtTurquoise = 63,
	DragodindeIndigoEtOrchidee = 64,
	DragodindeIndigoEtPourpre = 65,
	DragodindeIvoireEtTurquoise = 66,
	DragodindeIvoireEtOrchidee = 67,
	DragodindeIvoireEtPourpre = 68,
	DragodindeTurquoiseEtRousse = 69,
	DragodindeOrchideeEtRousse = 70,
	DragodindePourpreEtRousse = 71,
	DragodindeTurquoiseEtOrchidee = 72,
	DragodindeTurquoiseEtPourpre = 73,
	DragodindeDoreeSauvage = 74,
	DragodindeSquelette = 75,
	DragodindeOrchideeEtPourpre = 76,
	DragodindePruneEtAmande = 77,
	DragodindePruneEtDoree = 78,
	DragodindePruneEtEbene = 79,
	DragodindePruneEtEmeraude = 80,
	DragodindePruneEtIndigo = 82,
	DragodindePruneEtIvoire = 83,
	DragodindePruneEtRousse = 84,
	DragodindePruneEtTurquoise = 85,
	DragodindePruneEtOrchidee = 86,
	DragodindePruneEtPourpre = 87,
	DragodindeEnArmure = 88,
	DragodindeAPlumes = 89,
}
