// <auto-generated />
using Krosmoz.Servers.GameServer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Krosmoz.Servers.GameServer.Database.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Krosmoz.Servers.GameServer.Database.Models.Maps.MapRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("BlueCells")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("BottomCellId")
                        .HasColumnType("smallint");

                    b.Property<int>("BottomNeighborId")
                        .HasColumnType("int");

                    b.Property<int>("Capabilities")
                        .HasColumnType("int");

                    b.Property<string>("Cells")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasPriorityOnWorldMap")
                        .HasColumnType("bit");

                    b.Property<short?>("LeftCellId")
                        .HasColumnType("smallint");

                    b.Property<int>("LeftNeighborId")
                        .HasColumnType("int");

                    b.Property<int>("MerchantsMax")
                        .HasColumnType("int");

                    b.Property<bool>("Outdoor")
                        .HasColumnType("bit");

                    b.Property<bool>("PlacementGenDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("PrismAllowed")
                        .HasColumnType("bit");

                    b.Property<bool>("PvpDisabled")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("RedCells")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("RightCellId")
                        .HasColumnType("smallint");

                    b.Property<int>("RightNeighborId")
                        .HasColumnType("int");

                    b.Property<int>("SpawnDisabled")
                        .HasColumnType("int");

                    b.Property<int>("SubAreaId")
                        .HasColumnType("int");

                    b.Property<short?>("TopCellId")
                        .HasColumnType("smallint");

                    b.Property<int>("TopNeighborId")
                        .HasColumnType("int");

                    b.Property<int>("WorldMap")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("maps", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
